apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: httpserver-app
  name: httpserver-app
  namespace: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpserver-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpserver-app
    spec:
      containers:
      - image: brian880120/cncampa03-httpserver:v1
        name: httpserver
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
        - containerPort: 8080
      restartPolicy: Always
status: {}
